site: reasonable prototype
title: reasonable prototype
description: >-
  to be released
googlewebfonts: Noto+Sans:wght@400;700
lang: en-US
timezone: London
repo: https://github.com/reasonableprototype/reasonableprototype.github.io # site repo [optional]
data-theme: light # default theme "dark" | "light"

author:
  name: El No
  bio: sociologist
  username: reasonableprototype # general username
  github: reasonableprototype # github username
  twitter: reasonableprototype # twitter username
  email: your-email@email.com # email address

# URL settings
url: "https://reasonableprototype.github.io" #
baseurl: # leave blank if not wished
permalink: "https://reasonableprototype.github.io"
permalink: pretty


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


